pipeline {
    agent {
        docker { image 'node:16-alpine' }
    }
    
    stages {
        stage ('Version') {
            steps {
                sh 'node --version'
            }
        }
    }

    post {
        success {
            echo "build succeeded and found the versison number"
        }
        failure {
            echo "failed to retrive the version number"
        }
    }
}
